version: "3.9"
services:
  db:
    image: postgres:16
    container_name: gym_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gym_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # Opcional: S3 compatible para evidencias de pago
  minio:
    image: minio/minio:latest
    container_name: gym_minio
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

volumes:
  dbdata:
  miniodata:
